export const STELLAR_CONSTANTS = {
  MIN_BASE_FEE: 100,
  MAX_OPERATIONS_PER_TX: 100,
  TX_TIMEOUT_SECONDS: 300,
};

export const SOROBAN_CONSTANTS = {
  SIMULATION_LEDGER_BUFFER: 12,
  DEFAULT_TIMEOUT: 30,
};

export const HTTP_RESPONSE_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};
